
'use client'
import "./globals.css";
import { getAuth } from 'firebase/auth';
import { useState, useEffect } from 'react';

export default function RootLayout({ children }) {
  const [currentUser, setCurrentUser] = useState(null);

  useEffect(() => {
    const auth = getAuth();
    const unsubscribe = auth.onAuthStateChanged(user => {
      setCurrentUser(user);
    });

    // Cleanup function to unsubscribe from the listener
    return () => unsubscribe();
  }, []); // Empty dependency array ensures this effect runs only once

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}


