import "./globals.css";
import authOptions from '../app/api/auth/[...nextauth]/routes'
import SessionProvider from "./SessionProvider";
import SignIn from "./sign-in/page";
import Home from "./page";
import {getServerSession} from 'next-auth'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body >
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
